version: '3'

services:
  api-stock:
    container_name: api-stock
    build: .
    platform: linux/amd64 
    environment:
      - SECRET={SECRET}
      - DATABASE_URL={DATABASE_URL}
    ports:
      - "3333:3333"

    labels:
      - app.required_env=SECRET,DATABASE_URL
      - app.env.SECRET=Chave secreta da aplicação
      - app.env.DATABASE_URL=String de conexão com banco