name: Build e push das imagens (simples)

on:
  push:
    branches:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Configurar insecure registry
        run: |
          echo '{
            "insecure-registries": ["'${{ secrets.REGISTRY_URL }}'"]
          }' | sudo tee /etc/docker/daemon.json

          sudo systemctl restart docker

      - name: 🔐 Login no registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} \
            -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      # =========================
      # BACKEND
      # =========================
      - name: 🏗️ Build backend
        run: |
          docker build -t ${{ secrets.REGISTRY_IP }}/backend_stock:latest ./backend

      - name: 📤 Push backend
        run: |
          docker push ${{ secrets.REGISTRY_IP }}/backend_stock:latest

      # =========================
      # FRONTEND
      # =========================
      - name: 🏗️ Build frontend
        run: |
          docker build -t ${{ secrets.REGISTRY_IP }}/frontend_stock:latest ./frontend

      - name: 📤 Push frontend
        run: |
          docker push ${{ secrets.REGISTRY_IP }}/frontend_stock:latest